name: Release

on:
  push:
    branches:
      - 'release/**'

jobs:
  deploy:
    name: Publish to Play
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged != true
        run: exit 1

      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Retrieve access json
        env:
          play_access_json: ${{ secrets.play_access_json }}
        run: echo $play_access_json > app/keys/play_access.json

      - name: Retrieve upload keystore
        env:
          upload_keystore: ${{ secrets.upload_keystore }}
        run: echo $upload_keystore | base64 -di > app/keys/upload.keystore

      - name: Publish app to internal test track
        env:
          socket_weather_alias: ${{ secrets.socket_weather_alias }}
          socket_weather_password: ${{ secrets.socket_weather_password }}
        run: bash ./gradlew publishReleaseBundle

      - name: Update store listing
        run: bash ./gradlew publishListing
